  CREATE TABLE "IRMIS"."CS_TDL_ACCESS" 
   (	"ACC_ID" NUMBER(9,0) NOT NULL ENABLE, 
	"ACC_EMP_NO" NUMBER(9,0) NOT NULL ENABLE, 
	"ACC_TASK_GROUP" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"ACC_ORG" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"ACC_DUTY_TYPE" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"ACC_JUSTIFICATION" VARCHAR2(500 BYTE), 
	"ACC_IS_APPROVED" VARCHAR2(1 BYTE)
   )